Support batching of calls to `Documents.import_`
typesense/typesense-python pull request #22
Opened 2022-06-10 20:40 UTC by pratheekrebala

## Change Summary
This PR allows batching of calls to the `Documents.import_` method and allows user to provide a generator to the `import_` function. This provides some QoL improvements when working with large number of documents.

Specifically, the changes the signature of the `Documents.import_` method to allow passing any object of type `Iterable` as the `documents` argument and allows an additional keyword argument called `batch_size`.

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

2022-07-19 06:10 UTC, kishorenc requested changes

2022-07-19 06:10 UTC, kishorenc commented on typesense/documents.py
> +                    self.import_(batch, params)
Should be:

```
api_response = self.import_(batch, params)
```

Correct?

2022-07-20 20:55 UTC, pratheekrebala commented on typesense/documents.py
> +                    self.import_(batch, params)
Yep! I just fixed in 3c2f708

2022-07-21 01:49 UTC, kishorenc commented
Sorry, there's now a conflict because of the changes from https://github.com/typesense/typesense-python/pull/26/files that needs resolution.

2022-07-21 23:25 UTC, pratheekrebala commented
Resolved!

2022-07-21 23:49 UTC, pratheekrebala commented
Resolved!

2022-08-04 04:59 UTC, kishorenc approved these changes
Thank you for your contribution!

2022-08-04 04:59 UTC, merged